/**
 * Inline translation objects for KeepUI.
 *
 * These mirror `en.json`, `es.json` and `de.json` and are bundled directly
 * into the library so that no HTTP request is needed at runtime.
 *
 * > **Do not edit this file manually.**
 * > Keep it in sync with the JSON files inside `/i18n/`.
 */

import { KeepUiLanguage } from './translation-keys';

export interface KeepUiTranslationSchema {
  imagePreview: {
    selectImage: string;
    loading: string;
    previewAlt: string;
    errorUnexpected: string;
  };
}

const EN: KeepUiTranslationSchema = {
  imagePreview: {
    selectImage: 'Select image',
    loading: 'Loading…',
    previewAlt: 'Selected image preview',
    errorUnexpected: 'An unexpected error occurred',
  },
};

const ES: KeepUiTranslationSchema = {
  imagePreview: {
    selectImage: 'Seleccionar imagen',
    loading: 'Cargando…',
    previewAlt: 'Vista previa de imagen seleccionada',
    errorUnexpected: 'Ha ocurrido un error inesperado',
  },
};

const DE: KeepUiTranslationSchema = {
  imagePreview: {
    selectImage: 'Bild auswählen',
    loading: 'Laden…',
    previewAlt: 'Vorschau des ausgewählten Bildes',
    errorUnexpected: 'Ein unerwarteter Fehler ist aufgetreten',
  },
};

/** Map from locale code to its translation object. */
export const KEEPUI_TRANSLATIONS: Record<KeepUiLanguage, KeepUiTranslationSchema> = {
  en: EN,
  es: ES,
  de: DE,
};

