import {
  Component,
  ChangeDetectionStrategy,
  input,
  model,
  computed,
} from '@angular/core';
import { SignalTextareaResize, SignalTextareaWidth } from './signal-textarea.types';

/**
 * Signal-based accessible textarea component with character counter,
 * resize control, and integrated error display.
 *
 * The `value` and `touched` properties are `model()` signals so the component
 * integrates seamlessly with Angular signal-based forms.
 *
 * ```html
 * <keepui-signal-textarea
 *   label="Descripción"
 *   placeholder="Escribe aquí…"
 *   [rows]="5"
 *   [maxLength]="500"
 *   [(value)]="description"
 * />
 * ```
 */
@Component({
  selector: 'keepui-signal-textarea',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'block' },
  template: `
    <div class="flex flex-col gap-1" [class]="widthClass()">

      @if (label()) {
        <label [for]="textareaId()" class="text-sm text-ku-gray-text">
          {{ label() }}
          @if (required()) {
            <span class="text-ku-error-primary" aria-hidden="true"> *</span>
          }
        </label>
      }

      <textarea
        [id]="textareaId()"
        [value]="value()"
        [placeholder]="placeholder()"
        [rows]="rows()"
        [disabled]="disabled()"
        [attr.maxlength]="maxLength() ?? null"
        [attr.required]="required() ? true : null"
        [attr.aria-required]="required() ? true : null"
        [attr.aria-invalid]="showError() ? true : null"
        [attr.aria-describedby]="showError() ? errorId() : (maxLength() ? charCountId() : null)"
        class="bg-ku-primary border rounded-xl p-3 text-sm text-ku-primary-text
               placeholder:text-ku-gray-text outline-none transition-colors w-full
               disabled:opacity-50 disabled:cursor-not-allowed"
        [class]="textareaClasses()"
        (input)="onInput($event)"
        (blur)="onBlur()"
      ></textarea>

      <div class="flex items-start justify-between gap-2">

        <span
          [id]="errorId()"
          class="text-sm text-ku-error-primary"
          role="alert"
        >
          @if (showError()) {
            @if (errorMessage()) {
              {{ errorMessage() }}
            } @else if (errors().length > 0) {
              {{ errors()[0] }}
            }
          }
        </span>

        @if (maxLength()) {
          <span
            [id]="charCountId()"
            class="text-xs text-ku-gray-text ml-auto shrink-0"
            aria-live="polite"
            aria-atomic="true"
          >
            {{ charCount() }}&thinsp;/&thinsp;{{ maxLength() }}
          </span>
        }

      </div>

    </div>
  `,
})
export class SignalTextareaComponent {

  /** Optional label text rendered above the textarea. */
  readonly label = input<string>('');

  /** Placeholder passed to the underlying `<textarea>`. */
  readonly placeholder = input<string>('');

  /** Number of visible text rows. @default 4 */
  readonly rows = input<number>(4);

  /** Layout width of the wrapper. @default 'full' */
  readonly width = input<SignalTextareaWidth>('full');

  /** CSS `resize` behaviour. @default 'none' */
  readonly resize = input<SignalTextareaResize>('none');

  /** Marks the field as required. @default false */
  readonly required = input<boolean>(false);

  /** Human-readable error message. Takes precedence over `errors[0]`. */
  readonly errorMessage = input<string>('');

  /**
   * Array of error strings. The first item is displayed when `errorMessage` is empty.
   * Set together with `invalid=true` to trigger the error state.
   */
  readonly errors = input<readonly string[]>([]);

  /**
   * Stable `id` used to link the `<label>` with the `<textarea>`.
   * A random suffix is generated by default.
   */
  readonly textareaId = input<string>(
    `ku-textarea-${Math.random().toString(36).slice(2, 8)}`,
  );

  /** Disables the textarea. @default false */
  readonly disabled = input<boolean>(false);

  /** Maximum number of characters allowed. Shows a character counter when set. */
  readonly maxLength = input<number | undefined>(undefined);

  /**
   * Forces the error visual state regardless of the `touched` model.
   * Useful for external form validation. @default false
   */
  readonly invalid = input<boolean>(false);

  /** Current text value. Use `[(value)]` for two-way binding. */
  readonly value = model<string>('');

  /** Whether the control has been interacted with. Use `[(touched)]` for two-way binding. */
  readonly touched = model<boolean>(false);

  protected readonly errorId = computed(() => `${this.textareaId()}-error`);
  protected readonly charCountId = computed(() => `${this.textareaId()}-count`);

  protected readonly charCount = computed(() => this.value().length);

  protected readonly showError = computed(
    () =>
      this.touched() &&
      (this.invalid() || this.errorMessage().length > 0 || this.errors().length > 0),
  );

  protected readonly widthClass = computed<string>(() => {
    const map: Record<SignalTextareaWidth, string> = {
      full: 'w-full',
      half: 'w-1/2',
      auto: 'w-auto',
    };
    return map[this.width()];
  });

  protected readonly resizeClass = computed<string>(() => {
    const map: Record<SignalTextareaResize, string> = {
      none: 'resize-none',
      vertical: 'resize-y',
      horizontal: 'resize-x',
      both: 'resize',
    };
    return map[this.resize()];
  });

  protected readonly textareaClasses = computed(() => {
    const borderColor = this.showError()
      ? 'border-ku-error-primary'
      : 'border-ku-secondary-border focus-visible:border-ku-action-primary';
    return `${this.resizeClass()} ${borderColor}`;
  });

  protected onInput(event: Event): void {
    const target = event.target as HTMLTextAreaElement;
    this.value.set(target.value);
  }

  protected onBlur(): void {
    this.touched.set(true);
  }
}


